name: Deploy "Under Construction" Page
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
              <title>网站开发中</title>
              <style>
                  body { display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; font-family: Arial, sans-serif; }
                  .message { font-size: 2em; color: #333; }
              </style>
          </head>
          <body>
              <div class="message">拂来（ffffly）网站开发中，敬请期待！</div>
          </body>
          </html>' > index.html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
